name: 'Copilot User Management'
description: 'Optimize organization costs and seat usage by periodically removing unused Copilot for Business seat assignments.'
branding:
  icon: 'download'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  org_name: 
    description: 'Organization name'
    required: false
  ent_name: 
    description: 'Enterprise name'
    required: false    
  csv_path:
    description: 'CSV File path'
    required: true
runs:
  using: 'node20'
  main: 'app/index.js'
