name: 'Copilot User Management'
description: 'Retrieve Copilot seat usage for an enterprise or organization.'
branding:
  icon: download
  color: orange
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  org_name: 
    description: 'Organization name'
    required: false
  ent_name: 
    description: 'Enterprise name'
    required: false    
  csv_path:
    description: 'CSV File path'
    required: true
  inactive_only:
    description: 'Show only the inactive users from seat assignments'
    required: true
    default: 'false'
  inactive_days:
    description: 'Number of days to identify an inactive user.'
    required: true
    default: '25'    
runs:
  using: 'node20'
  main: 'app/index.js'
