name: 'Copilot User Management'
description: 'Regularly optimize cost and seat usage for an organization by removing unused Copilot for Business seat assignments from the Organization.'
branding:
  icon: 'download'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  org_name: 
    description: 'Organization name'
    required: true
  csv_path:
    description: 'CSV File path'
    required: true
  is_delete:
    description: 'Eliminate Inactive Users and Users inactive for the past n days'
    required: true
    type: 'boolean'
    default: false
  inactive_only:
    description: 'Remove only the inactive users from seat assignments'
    required: true
    type: 'boolean'
    default: false
  inactive_days:
    description: 'Number of days to identify an inactive user. Default to 25 days.'
    required: true
    default: '25'
runs:
  using: 'node20'
  main: 'app/index.js'
