    name: Copilot User Management to Report Inactive Users

    on:
      workflow_dispatch:
          inputs:
              org_name: 
                description: 'Organization name'
                required: true
                default: 'octodemo'
              csv_path:
                description: 'CSV File path'
                required: true
                default: 'data/Copilot-Usage-Report.csv'
              is_delete:
                description: 'Eliminate Inactive Users and Users inactive for the past n days'
                required: false
                type: boolean
                default: false
              inactive_only:
                description: 'Remove only the inactive users from seat assignments'
                required: false
                type: boolean
                default:  false
              inactive_days:
                description: 'Number of days to identify an inactive user. Default to 25 days.'
                required: false
                default: '25'

    jobs:
      first-job:
        runs-on: ubuntu-latest
        
        steps:
          - name: Copilot User Management
            uses: ambilykk/copilot-user-mgmt@main
            with:        
              GITHUB_TOKEN: ${{ secrets.GH_TOK }}
              org_name: ${{ inputs.org_name }} 
              csv_path: ${{ inputs.csv_path }} 
              is_delete: ${{ inputs.is_delete }}
              inactive_only: ${{ inputs.inactive_only }}
              inactive_days: ${{ inputs.inactive_days }}
        
          - name: Upload Copilot Usage Report for Inactive Users
            uses: actions/upload-artifact@v4
            with:
              name: Copilot Usage Report
              path: ${{ inputs.csv_path }}   
